repos:
  - repo: local
    hooks:
      - id: prettier-npx
        name: prettier (npx latest)
        entry: npx --yes prettier@latest --write
        language: system
        pass_filenames: true
        types_or:
          - javascript
          - jsx
          - ts
          - tsx
          - json
          - yaml
          - toml
          - css
          - scss
          - less
          - html
          - markdown
      - id: eslint-npx
        name: eslint (npx)
        entry: npx eslint --max-warnings=0 --fix
        language: system
        pass_filenames: true
        types_or:
          - javascript
          - jsx
          - ts
          - tsx

  - repo: local
    hooks:
      - id: commitlint
        name: commitlint
        entry: npx commitlint --edit
        language: system
        stages:
          - commit-msg
        pass_filenames: true
